### ISSUE TITLE
feat: Shortcode integration

### ISSUE THREAD

**Issue by jef** [shiraji/yet-another-emoji-support#57]
### Request

I'd like to see this plugin allow to toggle between printing the emoji and using the shortcode. Kind of how GitHub does it now.

Example:

![image](https://user-images.githubusercontent.com/12074633/77796135-212ef000-7045-11ea-9e01-0ff4ff73a451.png)

- [x] Use shortcode (prints `:100:`)
- [ ] Use shortcode (prints :100:)

Potentially helpful links:

- [emoji-cheat-sheet](https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md)
- [GitHub Emoji API](https://api.github.com/emojis)

**Comment by shiraji** [comment]
This plugin adds keyword, so that if you type "full", then it will show 💯 .

![image](https://user-images.githubusercontent.com/3675458/77816159-c14b4e80-7103-11ea-98f6-e3b373e48a25.png)

However, you are right, somehow, IntelliJ does not support content assist when developers types numbers/symbols only. It does not catch :100

![image](https://user-images.githubusercontent.com/3675458/77816171-d0320100-7103-11ea-823f-7c4520a96bba.png)

If it starts from character (e.g. h), it will catch "100"

![image](https://user-images.githubusercontent.com/3675458/77816144-a7aa0700-7103-11ea-9cd0-5a4f36004b2f.png)

Let me think how I can support this...

**Comment by shiraji** [comment]
I think [1.0.6](https://plugins.jetbrains.com/plugin/12512-yet-another-emoji-support/update/82017) support how you want to use this plugin. Please wait until JetBrains approves this update (according to them, it will take 2 business days)

**Comment by jef** [comment]
Oh wow... This is also interesting. That's a good find on fixing that!

I guess my original request was more along the lines of something like this:

When I type `:1st`, I get this emoji `🥇` after I accept the autocomplete. Which is great, but I was thinking that maybe we could have an option to print `:1st_place_medal:` instead of printing the emoji.

Hopefully that makes more sense. I don't know if it brings much benefit aside not printing unicode directly into our commits or terminals that don't support emoji.

**Comment by shiraji** [comment]
Ah, ok.

Actually, that was what I was thinking useful, so that I created the plugin a long time ago.

https://github.com/shiraji/emoji

However, a lot of people requested me to insert emoji directly. So, this plugin was developed.

Well, I could implement this feature in other plugin (whereas, other plugin uses really old emoji data which may ends up rewriting whole thing 😢...)

**Comment by jef** [comment]
Ahhhh. That makes sense to me. Maybe I can help with having an option in preferences to help toggle between the two outputs? Would that be something to consider?

**Comment by shiraji** [comment]
Well, it's kinda hard, thought. This plugin uses [official emoji characters](https://unicode.org/emoji/charts/full-emoji-list.html), not GitHub Emoji API. This plugin uses official emoji's both `CLDR Short Name` and `keywords` to make suggestion. There is no compatibility between official emoji and GitHub's emoji. For example, 💯's CLDR Short Name is "hundred points" and its keywords are "100", "full", and "score". GitHub emoji API is "100".

I think what you want to do is showing emoji when you want to review code at GitHub, right? If so, https://github.com/shiraji/emoji is better choice even thought it was only supported at commit dialog.

Well, I think it's time to reimplement https://github.com/shiraji/emoji

**Comment by jef** [comment]
> There is no compatibility between official emoji and GitHub's emoji. For example, 💯's CLDR Short Name is "hundred points" and its keywords are "100", "full", and "score". GitHub emoji API is "100".

That's a really good point. I don't want to introduce too much feature drift here.

> I think what you want to do is showing emoji when you want to review code at GitHub, right? If so, https://github.com/shiraji/emoji is better choice even thought currently it was only supported at commit dialog.

Yup! That's exactly it. I guess back then when I did the "+1", I was on the other side of that line 😆

**Comment by shiraji** [comment]
I'm going to close this issue. https://github.com/shiraji/emoji version 3.0.0 uses GitHub API emoji and it will insert :100: in commit dialog and markdown. It will take 2 business days to JetBrains approve the plugin update.
